#!/bin/bash
bin=`dirname "$0"`
bin=`cd $bin; pwd`

cd $bin

. ./env.sh

gofmt -w src
if [ $? != 0 ]; then
    echo "gofmt error"
    exit 1
fi

cd $bin/src/gin-server

go install
if [ $? != 0 ]; then
    echo -e "\e[31minstall \e[4m$t\e[0m\e[31m error\e[0m"
    exit 1
fi
echo -e "\e[32minstall \e[4m$t\e[0m\e[32m success\e[0m"
