app_name = "gin"

[server]
max_cpu		= 0
http_port	= 9090
pprof_port	= 6063
rest_port   = 7074
#单位为毫秒
read_timeout = 1000
write_timeout = 1000

[riskdb]
host	= "192.168.66.113"
port	= 3306
user	= "root"
pwd		= "123456"
db_name	= "risk"
max_idle	= 10
max_open	= 20
pool_size	= 20