app_name = "gin"

[server]
max_cpu		= 0
http_port	= 9090
pprof_port	= 6063
rest_port   = 7074
#单位为毫秒
read_timeout = 1000
write_timeout = 1000

[riskdb]
host	= "192.168.66.113"
port	= 3306
user	= "root"
pwd		= "123456"
db_name	= "risk"
max_idle	= 10
max_open	= 20
pool_size	= 20

#redis cache 无需持久化
[cache]
	[cache.1]
        host            = "127.0.0.1"
        port            = 6379
        pool_size       = 100
        max_idle        = 50
        #单位是毫秒
        idle_timeout    = 30000
        connect_timeout = 500
        read_timeout    = 3000
        write_timeout   = 3000